import type { Piece, User, WeatherData } from "./types";

export const DEMO_MODE = import.meta.env.VITE_DEMO_MODE === "true";

export const DEMO_USER: User = {
  id: "demo-user",
  identifiant: "demo",
  nom: "Démo",
  prenom: "Utilisateur",
  grade: "Général",
  role: "ADMIN",
  mustChangePassword: false,
  pieces: [],
};

const now = () => Date.now();

export const DEMO_PIECES: Piece[] = [
  {
    id: "1",
    numero: 1,
    nom: "ROVER-01",
    batterie: "Batterie",
    statut: "operational",
    temperature: 31.5,
    nombreTirs: 12,
    stockObus: 42,
    stockMax: 75,
    cadenceTir: 6,
    positionMGRS: "28PBB3082630335",
    lat: 14.7028,
    lng: -17.4215,
    azimutConsigne: 152.0,
    azimutReel: 154.2,
    giteConsigne: 0.0,
    giteReel: 0.8,
    dernierTir: now(),
    enTirEnCours: false,
    derniereActivite: now(),
    elevationReel: 1.2,
    azimutMil: 2741,
    giteMil: 14,
    elevationMil: 21,
  },
  {
    id: "2",
    numero: 4,
    nom: "ROVER-04",
    batterie: "Batterie",
    statut: "degraded",
    temperature: 44.2,
    nombreTirs: 8,
    stockObus: 28,
    stockMax: 75,
    cadenceTir: 6,
    positionMGRS: "28PBB3083230342",
    lat: 14.7035,
    lng: -17.4208,
    azimutConsigne: 152.0,
    azimutReel: 160.5,
    giteConsigne: 0.0,
    giteReel: -1.2,
    dernierTir: now(),
    enTirEnCours: false,
    derniereActivite: now(),
    elevationReel: 0.8,
    azimutMil: 2853,
    giteMil: -21,
    elevationMil: 14,
  },
  {
    id: "3",
    numero: 5,
    nom: "ECLAIREUR",
    batterie: "Batterie",
    statut: "operational",
    temperature: 29.0,
    nombreTirs: 0,
    stockObus: 0,
    stockMax: 0,
    cadenceTir: 0,
    positionMGRS: "28PBB3084530352",
    lat: 14.7045,
    lng: -17.4195,
    azimutConsigne: 186.0,
    azimutReel: 186.0,
    giteConsigne: 0.0,
    giteReel: 0.0,
    dernierTir: now(),
    enTirEnCours: false,
    derniereActivite: now(),
    elevationReel: 1.5,
    azimutMil: 3305,
    giteMil: 0,
    elevationMil: 27,
  },
  {
    id: "4",
    numero: 2,
    nom: "STATION_METEO",
    batterie: "Batterie",
    statut: "operational",
    temperature: 28.5,
    nombreTirs: 0,
    stockObus: 0,
    stockMax: 0,
    cadenceTir: 0,
    positionMGRS: "28PBB3082030339",
    lat: 14.7032,
    lng: -17.4220,
    azimutConsigne: 0,
    azimutReel: 0,
    giteConsigne: 0,
    giteReel: 0,
    dernierTir: now(),
    enTirEnCours: false,
    derniereActivite: now(),
    elevationReel: 0,
    azimutMil: 0,
    giteMil: 0,
    elevationMil: 0,
  },
];

export const DEMO_METEO: WeatherData = {
  temperature: 28.5,
  humidity: 68.0,
  pressure: 1013.2,
  windSpeed: 4.2,
  windDirection: 310.0,
};

/** id de la pièce ROVER-04, dont le statut oscille degraded ⇄ operational dans la simulation */
export const DEMO_FLAKY_PIECE_ID = "2";
