/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PiecesRouteImport } from './routes/pieces'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AlertesRouteImport } from './routes/alertes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PiecesPieceIdRouteImport } from './routes/pieces.$pieceId'
import { Route as AdminResponsablesRouteImport } from './routes/admin.responsables'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminConfigurationRouteImport } from './routes/admin.configuration'
import { Route as AdminCartesRouteImport } from './routes/admin.cartes'

const PiecesRoute = PiecesRouteImport.update({
  id: '/pieces',
  path: '/pieces',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertesRoute = AlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesPieceIdRoute = PiecesPieceIdRouteImport.update({
  id: '/$pieceId',
  path: '/$pieceId',
  getParentRoute: () => PiecesRoute,
} as any)
const AdminResponsablesRoute = AdminResponsablesRouteImport.update({
  id: '/admin/responsables',
  path: '/admin/responsables',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/admin/maintenance',
  path: '/admin/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigurationRoute = AdminConfigurationRouteImport.update({
  id: '/admin/configuration',
  path: '/admin/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCartesRoute = AdminCartesRouteImport.update({
  id: '/admin/cartes',
  path: '/admin/cartes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/change-password': typeof ChangePasswordRoute
  '/configuration': typeof ConfigurationRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/pieces': typeof PiecesRouteWithChildren
  '/admin/cartes': typeof AdminCartesRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/responsables': typeof AdminResponsablesRoute
  '/pieces/$pieceId': typeof PiecesPieceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/change-password': typeof ChangePasswordRoute
  '/configuration': typeof ConfigurationRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/pieces': typeof PiecesRouteWithChildren
  '/admin/cartes': typeof AdminCartesRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/responsables': typeof AdminResponsablesRoute
  '/pieces/$pieceId': typeof PiecesPieceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertes': typeof AlertesRoute
  '/change-password': typeof ChangePasswordRoute
  '/configuration': typeof ConfigurationRoute
  '/historique': typeof HistoriqueRoute
  '/login': typeof LoginRoute
  '/pieces': typeof PiecesRouteWithChildren
  '/admin/cartes': typeof AdminCartesRoute
  '/admin/configuration': typeof AdminConfigurationRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/responsables': typeof AdminResponsablesRoute
  '/pieces/$pieceId': typeof PiecesPieceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertes'
    | '/change-password'
    | '/configuration'
    | '/historique'
    | '/login'
    | '/pieces'
    | '/admin/cartes'
    | '/admin/configuration'
    | '/admin/maintenance'
    | '/admin/responsables'
    | '/pieces/$pieceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertes'
    | '/change-password'
    | '/configuration'
    | '/historique'
    | '/login'
    | '/pieces'
    | '/admin/cartes'
    | '/admin/configuration'
    | '/admin/maintenance'
    | '/admin/responsables'
    | '/pieces/$pieceId'
  id:
    | '__root__'
    | '/'
    | '/alertes'
    | '/change-password'
    | '/configuration'
    | '/historique'
    | '/login'
    | '/pieces'
    | '/admin/cartes'
    | '/admin/configuration'
    | '/admin/maintenance'
    | '/admin/responsables'
    | '/pieces/$pieceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertesRoute: typeof AlertesRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ConfigurationRoute: typeof ConfigurationRoute
  HistoriqueRoute: typeof HistoriqueRoute
  LoginRoute: typeof LoginRoute
  PiecesRoute: typeof PiecesRouteWithChildren
  AdminCartesRoute: typeof AdminCartesRoute
  AdminConfigurationRoute: typeof AdminConfigurationRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminResponsablesRoute: typeof AdminResponsablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pieces': {
      id: '/pieces'
      path: '/pieces'
      fullPath: '/pieces'
      preLoaderRoute: typeof PiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertes': {
      id: '/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AlertesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces/$pieceId': {
      id: '/pieces/$pieceId'
      path: '/$pieceId'
      fullPath: '/pieces/$pieceId'
      preLoaderRoute: typeof PiecesPieceIdRouteImport
      parentRoute: typeof PiecesRoute
    }
    '/admin/responsables': {
      id: '/admin/responsables'
      path: '/admin/responsables'
      fullPath: '/admin/responsables'
      preLoaderRoute: typeof AdminResponsablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuration': {
      id: '/admin/configuration'
      path: '/admin/configuration'
      fullPath: '/admin/configuration'
      preLoaderRoute: typeof AdminConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cartes': {
      id: '/admin/cartes'
      path: '/admin/cartes'
      fullPath: '/admin/cartes'
      preLoaderRoute: typeof AdminCartesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PiecesRouteChildren {
  PiecesPieceIdRoute: typeof PiecesPieceIdRoute
}

const PiecesRouteChildren: PiecesRouteChildren = {
  PiecesPieceIdRoute: PiecesPieceIdRoute,
}

const PiecesRouteWithChildren =
  PiecesRoute._addFileChildren(PiecesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertesRoute: AlertesRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ConfigurationRoute: ConfigurationRoute,
  HistoriqueRoute: HistoriqueRoute,
  LoginRoute: LoginRoute,
  PiecesRoute: PiecesRouteWithChildren,
  AdminCartesRoute: AdminCartesRoute,
  AdminConfigurationRoute: AdminConfigurationRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminResponsablesRoute: AdminResponsablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
